spring:
  shardingsphere:
    datasource:
      # ??????
      names: master0,slave0,slave1
      # ?????????
      master0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.6.128:3306/test?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
      # ?????????
      slave0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.6.128:3307/test?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
      # ?????????
      slave1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.6.128:3308/test?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
    rules:
      replica-query:
        data-sources:
          ds0:
            write-data-source-name: master0
          ds1:
            read-data-source-names: slave0,slave1
            load-balancer-name: round_robin
        loadBalancers:
          round_robin:
            type: ROUND_ROBIN
            props:
              x: x
    props:
      sql:
        show: true
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: io.github.linxiaobaixcg.domain
